import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cloudinary Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>Cloudinary Demo</h1>
      </Main>
    </div>
  );
}

const Main = styled.main`
  text-align: center;
`;
