import Head from "next/head";
import styled from "styled-components";
import ImageList from "../components/ImageList";
import ImageUploadForm from "../components/ImageUploadForm";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Cloudinary Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>Cloudinary Demo</h1>
        <StyledUpload>
          <ImageUploadForm />
        </StyledUpload>
        <ImageList />
      </Main>
    </div>
  );
}

const Main = styled.main`
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
`;
const StyledUpload = styled.div`
  width: 90%;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;

  border: 1px solid #ccc;
  border-radius: 0.5rem;
  padding: 4rem;
`;
